// ---------- wallet connect + live testnet contract calls ----------
// PERPETUA_DEPLOYMENT is filled in once the vault contracts are broadcast
// to a public testnet (see chain/deployed.<network>.json, generated by
// `npx hardhat run scripts/deploy.js --network <network>`). Until then
// this stays null and the site falls back to the illustrative demo math.
// Wallet connect itself works regardless — it only talks to the visitor's
// own wallet extension, never anything this site or its build controls.
const PERPETUA_DEPLOYMENT = null;
/* Example, once deployed:
const PERPETUA_DEPLOYMENT = {
  chainId: 11155111,
  chainName: "Sepolia",
  contracts: {
    DynamoVault: "0x...",
    DynamoGasSponsor: "0x...",
    USDG: "0x...",
  },
  stocks: {
    AAPL: { token: "0x...", targetBps: 4000 },
    NVDA: { token: "0x...", targetBps: 3500 },
    TSLA: { token: "0x...", targetBps: 2500 },
  },
  policyId: "0x...",
};
*/

const ERC20_ABI = [
  "function decimals() view returns (uint8)",
  "function balanceOf(address) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
];

const VAULT_ABI = [
  "function deposit(uint256 usdgAmount, uint256[] minOuts) returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function totalAssetsValueUsd() view returns (uint256)",
  "function accrueAndFundKeeperGas(uint256 minEthOut) returns (uint256)",
];

(function () {
  var walletBtn = document.getElementById("walletBtn");
  if (!walletBtn) return;

  var provider = null;
  var signer = null;
  var address = null;

  function short(a) {
    return a.slice(0, 6) + "…" + a.slice(-4);
  }
  function setStatus(label) {
    walletBtn.textContent = label;
  }

  async function connect() {
    if (!window.ethereum) {
      window.open("https://metamask.io/download/", "_blank", "noopener");
      return;
    }
    try {
      provider = new ethers.BrowserProvider(window.ethereum);
      var accounts = await provider.send("eth_requestAccounts", []);
      address = accounts[0];
      signer = await provider.getSigner();
      setStatus(short(address));
      walletBtn.classList.add("connected");
    } catch (e) {
      console.warn("Perpetua: wallet connect rejected or failed", e);
    }
  }

  walletBtn.addEventListener("click", function () {
    if (!address) connect();
  });

  if (window.ethereum && window.ethereum.on) {
    window.ethereum.on("accountsChanged", function (accounts) {
      if (!accounts.length) {
        address = null;
        signer = null;
        walletBtn.classList.remove("connected");
        setStatus("Connect");
      } else {
        address = accounts[0];
        setStatus(short(address));
      }
    });
    window.ethereum.on("chainChanged", function () {
      window.location.reload();
    });
  }

  // ---- real deposit / sweep, used only once PERPETUA_DEPLOYMENT is set ----
  window.perpetuaLiveDeposit = async function (usdgAmount) {
    if (!PERPETUA_DEPLOYMENT || !signer) return false;
    var c = PERPETUA_DEPLOYMENT.contracts;
    var usdg = new ethers.Contract(c.USDG, ERC20_ABI, signer);
    var vault = new ethers.Contract(c.DynamoVault, VAULT_ABI, signer);
    var amount = ethers.parseEther(String(usdgAmount));
    await (await usdg.approve(c.DynamoVault, amount)).wait();
    var minOuts = Object.keys(PERPETUA_DEPLOYMENT.stocks).map(function () {
      return 0;
    });
    await (await vault.deposit(amount, minOuts)).wait();
    return true;
  };

  window.perpetuaLiveSweep = async function () {
    if (!PERPETUA_DEPLOYMENT || !signer) return false;
    var vault = new ethers.Contract(PERPETUA_DEPLOYMENT.contracts.DynamoVault, VAULT_ABI, signer);
    var tx = await vault.accrueAndFundKeeperGas(0);
    await tx.wait();
    return true;
  };

  window.PERPETUA_DEPLOYMENT = PERPETUA_DEPLOYMENT;
})();
