// ---------- wallet connect + live testnet contract calls ----------
// DYNAMO_DEPLOYMENT is filled in once the contracts are broadcast to a
// public testnet (see chain/deployed.<network>.json, generated by
// `npx hardhat run scripts/deploy.js --network <network>`). Until then
// this stays null and the site falls back to the illustrative demo math
// in script.js — wallet connect itself still works either way.
const DYNAMO_DEPLOYMENT = null;
/* Example, once deployed:
const DYNAMO_DEPLOYMENT = {
  chainId: 11155111,
  chainName: "Sepolia",
  contracts: {
    DynamoVault: "0x...",
    DynamoGasSponsor: "0x...",
    USDG: "0x...",
  },
  stocks: {
    AAPL: { token: "0x...", targetBps: 4000 },
    NVDA: { token: "0x...", targetBps: 3500 },
    TSLA: { token: "0x...", targetBps: 2500 },
  },
  policyId: "0x...",
};
*/

const ERC20_ABI = [
  "function decimals() view returns (uint8)",
  "function balanceOf(address) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
];

const VAULT_ABI = [
  "function deposit(uint256 usdgAmount, uint256[] minOuts) returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function totalAssetsValueUsd() view returns (uint256)",
  "function accrueAndFundKeeperGas(uint256 minEthOut) returns (uint256)",
  "function assetCount() view returns (uint256)",
  "event KeeperGasFunded(uint256 feeUsdg, uint256 ethFunded)",
];

const GAS_SPONSOR_ABI = ["function spendableNow(bytes32 policyId) view returns (uint256)"];

(() => {
  const walletBtn = document.getElementById("walletBtn");
  if (!walletBtn) return;

  let provider = null;
  let signer = null;
  let address = null;

  const short = (a) => a.slice(0, 6) + "…" + a.slice(-4);

  function setStatus(label) {
    walletBtn.textContent = label;
  }

  async function refreshLiveState() {
    if (!DYNAMO_DEPLOYMENT || !provider) return;
    try {
      const vault = new ethers.Contract(DYNAMO_DEPLOYMENT.contracts.DynamoVault, VAULT_ABI, provider);
      const totalUsd = await vault.totalAssetsValueUsd();
      const totalEl = document.getElementById("basketTotal");
      if (totalEl) totalEl.textContent = "$" + Number(ethers.formatEther(totalUsd)).toLocaleString("en-US", { maximumFractionDigits: 0 });
    } catch (e) {
      console.warn("Dynamo: live state refresh failed", e);
    }
  }

  async function connect() {
    if (!window.ethereum) {
      window.open("https://metamask.io/download/", "_blank", "noopener");
      return;
    }
    try {
      provider = new ethers.BrowserProvider(window.ethereum);
      const accounts = await provider.send("eth_requestAccounts", []);
      address = accounts[0];
      signer = await provider.getSigner();
      setStatus(short(address));
      walletBtn.classList.add("connected");
      await refreshLiveState();
    } catch (e) {
      console.warn("Dynamo: wallet connect rejected or failed", e);
    }
  }

  walletBtn.addEventListener("click", () => {
    if (!address) connect();
  });

  if (window.ethereum) {
    window.ethereum.on?.("accountsChanged", (accounts) => {
      if (!accounts.length) {
        address = null;
        signer = null;
        walletBtn.classList.remove("connected");
        setStatus("Connect");
      } else {
        address = accounts[0];
        setStatus(short(address));
      }
    });
    window.ethereum.on?.("chainChanged", () => window.location.reload());
  }

  // ---- real deposit / sweep, used only once DYNAMO_DEPLOYMENT is set ----
  window.dynamoLiveDeposit = async function (usdgAmount) {
    if (!DYNAMO_DEPLOYMENT || !signer) return false;
    const { DynamoVault, USDG } = DYNAMO_DEPLOYMENT.contracts;
    const usdg = new ethers.Contract(USDG, ERC20_ABI, signer);
    const vault = new ethers.Contract(DynamoVault, VAULT_ABI, signer);
    const amount = ethers.parseEther(String(usdgAmount));
    await (await usdg.approve(DynamoVault, amount)).wait();
    const minOuts = Object.keys(DYNAMO_DEPLOYMENT.stocks).map(() => 0);
    await (await vault.deposit(amount, minOuts)).wait();
    await refreshLiveState();
    return true;
  };

  window.dynamoLiveSweep = async function () {
    if (!DYNAMO_DEPLOYMENT || !signer) return false;
    const vault = new ethers.Contract(DYNAMO_DEPLOYMENT.contracts.DynamoVault, VAULT_ABI, signer);
    const tx = await vault.accrueAndFundKeeperGas(0);
    await tx.wait();
    await refreshLiveState();
    return true;
  };

  window.DYNAMO_DEPLOYMENT = DYNAMO_DEPLOYMENT;
})();
