/**
 * Generates supabase/seed.sql from the Demo Mode dataset so production and demo
 * share one fictional fixture set. Run: npm run db:seed:generate
 *
 * Note: profiles reference auth.users; the fictional demo users are inserted
 * into auth.users with placeholder identities so foreign keys resolve. They
 * cannot sign in (no password). Delete them before going live with real users.
 */
import { writeFileSync } from "node:fs";
import { buildDemoDataset } from "../src/lib/demo/seed";

const dataset = buildDemoDataset(new Date());

function lit(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (Array.isArray(value)) return `array[${value.map(lit).join(", ")}]::text[]`;
  if (typeof value === "object") return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

// Deterministic UUIDs for fictional users (valid v4-shaped, fixed namespaces).
function uuidFor(id: string): string {
  let h = 0;
  for (const ch of id) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  const hex = h.toString(16).padStart(8, "0");
  return `00000000-0000-4000-8000-${hex}0000`;
}

const userIds = new Map(dataset.profiles.map((p) => [p.id, uuidFor(p.id)]));
const uid = (id: string) => userIds.get(id) ?? id;

const lines: string[] = ["-- Generated by scripts/generate-seed-sql.ts — fictional demo data. Do not treat as real projects.", "begin;"];
const insert = (table: string, rows: Record<string, unknown>[]) => {
  if (!rows.length) return;
  const cols = Object.keys(rows[0]!);
  lines.push(`insert into public.${table} (${cols.join(", ")}) values`);
  lines.push(rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(", ")})`).join(",\n") + "\non conflict do nothing;");
};

lines.push(
  "insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at) values",
  dataset.profiles
    .map((p) => `  ('${uid(p.id)}', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '${p.username}@demo.shiptrace.example', '', now(), '{}'::jsonb, now(), now())`)
    .join(",\n") + "\non conflict do nothing;",
);

insert(
  "profiles",
  dataset.profiles.map((p) => ({
    id: uid(p.id),
    username: p.username,
    display_name: p.displayName,
    role: p.role === "guest" ? "user" : p.role,
    bio: p.bio,
    watchlist_public: p.watchlistPublic,
    accepted_evidence_count: p.acceptedEvidenceCount,
    helpful_corrections_count: p.helpfulCorrectionsCount,
    is_demo: true,
    created_at: p.createdAt,
  })),
);
insert(
  "projects",
  dataset.projects.map((p) => ({
    id: p.id,
    slug: p.slug,
    name: p.name,
    description: p.description,
    category: p.category,
    ecosystem: p.ecosystem,
    official_url: p.officialUrl,
    status: p.status,
    data_completeness: p.dataCompleteness,
    last_verified_at: p.lastVerifiedAt,
    is_demo: true,
    transparency: p.transparency,
    created_at: p.createdAt,
    updated_at: p.updatedAt,
  })),
);
insert("project_links", dataset.projects.flatMap((p) => p.links.map((l) => ({ id: l.id, project_id: p.id, label: l.label, url: l.url, kind: l.kind }))));
insert(
  "milestones",
  dataset.milestones.map((m) => ({
    id: m.id,
    project_id: m.projectId,
    title: m.title,
    commitment_paraphrase: m.commitmentParaphrase,
    source_url: m.sourceUrl,
    source_accessed_at: m.sourceAccessedAt,
    claim_date: m.claimDate,
    deadline: m.deadline,
    original_deadline: m.originalDeadline,
    importance: m.importance,
    status: m.status,
    moderator_approved: m.moderatorApproved,
    moderator_note: m.moderatorNote,
    delivered_at: m.deliveredAt,
    has_updated_explanation: m.hasUpdatedExplanation,
    audit_id: m.auditId,
    created_at: m.createdAt,
    updated_at: m.updatedAt,
  })),
);
insert(
  "evidence",
  dataset.evidence.map((e) => ({
    id: e.id,
    project_id: e.projectId,
    milestone_id: e.milestoneId,
    url: e.url,
    type: e.type,
    title: e.title,
    summary: e.summary,
    published_at: e.publishedAt,
    accessed_at: e.accessedAt,
    submitter_id: uid(e.submitterId),
    submitter_name: e.submitterName,
    submitter_kind: e.submitterKind,
    review_state: e.reviewState,
    review_reason: e.reviewReason,
    reviewed_by_id: e.reviewedById ? uid(e.reviewedById) : null,
    reviewed_at: e.reviewedAt,
    support_count: e.supportCount,
    challenge_count: e.challengeCount,
    conflict_of_interest: e.conflictOfInterest,
    audit_id: e.auditId,
    created_at: e.createdAt,
  })),
);
insert(
  "milestone_status_events",
  dataset.statusEvents.map((s) => ({
    id: s.id,
    milestone_id: s.milestoneId,
    project_id: s.projectId,
    actor_id: s.actorId === "system" ? "system" : uid(s.actorId),
    actor_name: s.actorName,
    actor_kind: s.actorKind,
    prior_status: s.priorStatus,
    new_status: s.newStatus,
    reason: s.reason,
    evidence_ids: s.evidenceIds,
    audit_id: s.auditId,
    created_at: s.createdAt,
  })),
);
insert(
  "disputes",
  dataset.disputes.map((d) => ({
    id: d.id,
    project_id: d.projectId,
    milestone_id: d.milestoneId,
    evidence_id: d.evidenceId,
    kind: d.kind,
    submitter_id: uid(d.submitterId),
    submitter_name: d.submitterName,
    submitter_kind: d.submitterKind,
    claim: d.claim,
    source_url: d.sourceUrl,
    state: d.state,
    resolution: d.resolution,
    resolved_by_id: d.resolvedById ? uid(d.resolvedById) : null,
    resolved_at: d.resolvedAt,
    created_at: d.createdAt,
  })),
);
insert("github_repositories", dataset.githubRepositories.map((r) => ({ id: r.id, project_id: r.projectId, owner: r.owner, repo: r.repo, url: r.url, is_primary: r.isPrimary })));
insert(
  "github_snapshots",
  dataset.githubSnapshots.map((s) => ({
    id: s.id,
    repository_id: s.repositoryId,
    project_id: s.projectId,
    default_branch: s.defaultBranch,
    stars: s.stars,
    open_issues: s.openIssues,
    latest_release_tag: s.latestReleaseTag,
    latest_release_at: s.latestReleaseAt,
    releases_last_90d: s.releasesLast90d,
    tags_last_90d: s.tagsLast90d,
    active_weeks_last_12: s.activeWeeksLast12,
    last_push_at: s.lastPushAt,
    source: s.source,
    retrieved_at: s.retrievedAt,
  })),
);
insert("website_endpoints", dataset.endpoints.map((e) => ({ id: e.id, project_id: e.projectId, label: e.label, url: e.url, approved: e.approved })));
insert(
  "website_checks",
  dataset.websiteChecks.map((c) => ({ id: c.id, endpoint_id: c.endpointId, project_id: c.projectId, http_status: c.httpStatus, ok: c.ok, latency_ms: c.latencyMs, error: c.error, checked_at: c.checkedAt })),
);
insert(
  "ship_score_snapshots",
  dataset.scoreSnapshots.map((s) => ({
    id: s.id,
    project_id: s.projectId,
    total: s.total,
    components: s.components,
    confidence: s.confidence,
    data_completeness: s.dataCompleteness,
    formula_version: s.formulaVersion,
    insufficient_data: s.insufficientData,
    insufficient_reasons: s.insufficientReasons,
    explanation: s.explanation,
    calculated_at: s.calculatedAt,
  })),
);
insert(
  "feed_events",
  dataset.feedEvents.map((f) => ({
    id: f.id,
    type: f.type,
    project_id: f.projectId,
    milestone_id: f.milestoneId,
    evidence_id: f.evidenceId,
    title: f.title,
    summary: f.summary,
    source_url: f.sourceUrl,
    occurred_at: f.occurredAt,
    verified: f.verified,
  })),
);
insert("watchlists", dataset.watchlists.map((w) => ({ id: w.id, user_id: uid(w.userId), name: w.name, is_public: w.isPublic })));
insert("watchlist_items", dataset.watchlistItems.map((i) => ({ id: i.id, watchlist_id: i.watchlistId, project_id: i.projectId, added_at: i.addedAt })));
insert("user_badges", dataset.userBadges.map((b) => ({ user_id: uid(b.userId), badge_id: b.badgeId, awarded_at: b.awardedAt })));
insert(
  "admin_audit_log",
  dataset.adminAudit.map((a) => ({
    id: a.id,
    actor_id: uid(a.actorId),
    actor_name: a.actorName,
    action: a.action,
    target_type: a.targetType,
    target_id: a.targetId,
    reason: a.reason,
    before: a.before,
    after: a.after,
    created_at: a.createdAt,
  })),
);
lines.push("commit;");

writeFileSync("supabase/seed.sql", lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql: ${dataset.projects.length} projects, ${dataset.milestones.length} milestones, ${dataset.evidence.length} evidence records.`);
